name: app_roffo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # --- Firebase (core para salud, auth, base datos, login google)
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.13.6
  google_sign_in: ^6.2.5

  # --- Paquetes extra para funcionalidades comunes
  intl: ^0.19.0
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # --- Assets disponibles en la app (respetar rutas y nombres)
  assets:
    - assets/logo_hospi.jpg
    - assets/banner_home.png
    - assets/google_logo.png
    - assets/images/ilustracion_historia_clinica.png